### ISSUE TITLE
Error while running notify after installing.

### ISSUE THREAD

**Issue by parmanand99** [projectdiscovery/notify#112]
I am root user but still I am getting this
[FTL] Could not create runner: could not open provider config file: open /home/user/.config/notify/provider-config.yaml: no such file or directory.

 Notify version: latest i.e.  1.0.1

Steps To Reproduce:

Example: steps to reproduce the behavior:
1. Run 'notify ..'
2. See error...

**Comment by ehsandeep** [comment]
@parmanand99 see https://github.com/projectdiscovery/notify#provider-config, you need to create the provider config file with required information.

**Comment by parmanand99** [comment]
Thankyou  @ehsandeep , I have mistakenly not read that line for creation of file on readme.
