### ISSUE TITLE
WINDOWS ERROR

### ISSUE THREAD

**Issue by balook** [projectdiscovery/notify#12]
[←[1;31mFTL←[0m] The program is not running as root and unable to access raw sockets

**Comment by bauthard** [comment]
@balook we have added notify support for windows in the latest [release](https://github.com/projectdiscovery/notify/releases).

**Comment by balook** [comment]
u didnt created intercept support for windows  ....release for its too

**Comment by bauthard** [comment]
Unfortunately `intercept` can not be supported for Windows, as indicated in the other issue, for obtaining `biid` on windows you need to perform a manual steps as listed here https://github.com/projectdiscovery/notify/issues/5

**Comment by balook** [comment]
can u detail the steps to get biid from wireshark
