### ISSUE TITLE
not able to  install intercept 

### ISSUE THREAD

**Issue by abdoulhacker** [projectdiscovery/notify#14]
sddddd@hacker:~$ go get -u -v github.com/projectdiscovery/notify/cmd/intercept
github.com/projectdiscovery/notify (download)
github.com/projectdiscovery/collaborator (download)
github.com/google/gopacket (download)
github.com/projectdiscovery/gologger (download)
github.com/logrusorgru/aurora (download)
github.com/google/gopacket/pcap
# github.com/google/gopacket/pcap
go/src/github.com/google/gopacket/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by bauthard** [comment]
Hi @abdoulhacker, 

Make sure you are using go modules:- 

```
GO111MODULE=on go get -u -v github.com/projectdiscovery/notify/cmd/intercept
```

**Comment by abdoulhacker** [comment]
the problem is with the module intercept

go get -u -v github.com/projectdiscovery/notify/cmd/intercept

github.com/projectdiscovery/notify (download)
github.com/projectdiscovery/collaborator (download)
github.com/google/gopacket (download)
github.com/projectdiscovery/gologger (download)
github.com/logrusorgru/aurora (download)
github.com/google/gopacket/pcap
# github.com/google/gopacket/pcap
go/src/github.com/google/gopacket/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by DeC1pher** [comment]
Had the same issue and fixed it with installing libpcap-dev

`apt-get install libpcap-dev`

Cheers
