### ISSUE TITLE
Support for markdown format in telegram

### ISSUE THREAD

**Issue by zachi40** [projectdiscovery/notify#154]
hi
Telegram has added support for markdown v2
maybe you can add support for this option in the settings file

https://stackoverflow.com/questions/50770235/how-to-use-markdown-in-telegram-i-want-to-send-message-with-hyperlink

thank you

**Comment by zachi40** [comment]
I found who do that...
I add some code to the file "pkg\providers\telegram\telegram.go"

After line 22 
```
 TelegramParseMode string `yaml:"telegram_parsemode,omitempty"`
```
And on line 42

```
url := fmt.Sprintf("telegram://%s@telegram?channels=%s&parsemode=%s", pr.TelegramAPIKey, pr.TelegramChatID, pr.TelegramParseMode)

```
on config file I add the property
```
telegram_parsemode: MarkdownV2
```
 
now it is support the parse mode : None, Markdown, HTML, MarkdownV2

Thank you

**Comment by ehsandeep** [comment]
@zachi40 this is now supported with the latest release - https://github.com/projectdiscovery/notify/releases/tag/v1.0.3

```
    telegram_parsemode: "Markdown"
```
