### ISSUE TITLE
Feature Request - Add Delay Option

### ISSUE THREAD

**Issue by coffeegist** [projectdiscovery/notify#159]
### Please describe your feature request:
Currently, notify only supports the `-rl` rate limit option which has a max limit of 1 request per second. This is too much for some services such as Microsoft Teams connectors and can cause temporary lockouts. (https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#rate-limiting-for-connectors) 

By adding a `-delay` flag as well (consisting with other PD tools), we could gain better control over the rate at which notifications are sent and avoid having notifications be temporarily blackholed. 

### Describe the use case of this feature:
As a user, I need to limit my notifications to not exceed 30 requests per hour. To accomplish this, I could use the flag, `-delay 2`, to add a 2-second delay between each request.

 ```
 -delay int             delay between requests in seconds (0 to disable) (default 0)
 ```

**Comment by ehsandeep** [comment]
@coffeegist this is now supported in the dev version of the project using `-d` option.

**Comment by ehsandeep** [comment]
New release is pushed now - https://github.com/projectdiscovery/notify/releases/tag/v1.0.3
