### ISSUE TITLE
unable to use CliFormat to override ConfigFormat

### ISSUE THREAD

**Issue by fopina** [projectdiscovery/notify#161]
https://github.com/projectdiscovery/notify/blob/c9f7cc3025f5e400aeabd821686377c2d796cbf7/pkg/utils/utils.go#L25

If `ConfigFormat` for a given provider is `testing {{data}}` and, using the cli flag, I try to override with `{{data}}` (aka defaultFormat), it will be ignored.

Is there any reason for that condition or could it be removed?

**Comment by ehsandeep** [comment]
@fopina should be fixed with https://github.com/projectdiscovery/notify/pull/162, thanks for reporting this.

**Comment by ehsandeep** [comment]
@fopina should be fixed with the latest release - https://github.com/projectdiscovery/notify/releases/tag/v1.0.3, thanks again for reporting this.
