### ISSUE TITLE
custom_webhook_url is misspelled

### ISSUE THREAD

**Issue by pry0cc** [projectdiscovery/notify#170]
### Current Behavior:
custom_webook_url is typo'd

### Steps To Reproduce:
put custom_webhook_url in a configuration file, try notify, you will receive this error `Post "": unsupported protocol scheme ""`

### Anything else:
I would fix it myself but I'm in a hurry, remember to update the tests too!

**Comment by ehsandeep** [comment]
It should be fixed with https://github.com/projectdiscovery/notify/pull/172, @pry0cc. Thank you for flagging this.
