### ISSUE TITLE
Microsoft Teams as supported output platform

### ISSUE THREAD

**Issue by mzpqnxow** [projectdiscovery/notify#174]
It would be useful for some users if Microsoft Teams was supported as a publishing/output platform

Microsoft Teams includes quite a bit, so to clarify- this feature would be similar to the Slack and Discord platforms. Keeping simple, just publishing as a message in Teams chat to a channel/room or user

Teams is much more commonly used in the enterprise space when compared with Slack and Discord, which are both used widely by non-corporate humans and I realize this may provide negligible value to your core demographic as a result, unfortunately

Like everything I assume this comes down to cost/benefit (and/or if there are resources available for new development on the project for new features)

Unfortunately I've not worked with the Teams APIs at all so I can't comment on how extensive the work required to support it is. I suspect the Teams APIs are a little more involved than Slack and Discord but I can't imagine it being much different in terms of the pattern- authenticate/create authentication context, publish message

If you don't feel the effort would provide enough value, or would like to defer indefinitely, please feel free to close this issue out

Thanks for your work on this project. Thanks also for your consideration for this as a feature

**Comment by ehsandeep** [comment]
@mzpqnxow this is already supported, actually, but there was a known issue related to webhook URL format of MS Teams that was tracked in https://github.com/projectdiscovery/notify/issues/156 and now fixed with https://github.com/projectdiscovery/notify/pull/175, new release should be out soon.

**Comment by mzpqnxow** [comment]
Terrific, thanks! Apologies for not looking more closely
