### ISSUE TITLE
Notify doesn't work with telegram+collaborator

### ISSUE THREAD

**Issue by riramar** [projectdiscovery/notify#20]
This works perfect since I can see a "x" message in my telegram bot.

echo x | notify -telegram -telegram-api-key XXXX -telegram-chat-id XXXX

This also works fine since I see the burp collaborator interactions.

notify -biid 'XXXXXXXXXXXXXXXXXXXXXXXXXX'

But this doesn't work since I don't see any burp collaborator interaction in my telegram bot.

notify -biid 'XXXXXXXXXXXXXXXXXXXXXXXXXX' -telegram -telegram-api-key XXXX -telegram-chat-id XXXX

**Comment by bauthard** [comment]
@riramar burp collaborator interaction supported for **slack** and **discord** platform only due to formatting issue, we will update the readme to add this info.

**Comment by ehsandeep** [comment]
Closing as this is intended behavior
