### ISSUE TITLE
[Issue] /root/.config/notify/notify.conf file not found 

### ISSUE THREAD

**Issue by XPr3dat0r** [projectdiscovery/notify#23]

**Comment by slayer321** [comment]
yeah ... I got the same error I guess after moving to "/notify/cmd/notify"  there is no folder to move it to /usr/bin/local dir

**Comment by ehsandeep** [comment]
@XPr3dat0r what system are you using to install notify?

@slayer321 additionally you can created config file with `nano $HOME/.config/notify/notify.conf` and configure your keys.
