### ISSUE TITLE
SMTP fails when password contains octothorpe ("#") character

### ISSUE THREAD

**Issue by ossumpossum** [projectdiscovery/notify#255]
### Current Behavior: When attempting to use SMTP, I receive the following error:

[ERR] failed to send smtp notification for id: email : parse "smtp://test@example.com:xxxxx": invalid port ":xxxxx" after host

(output has been sanitized) The "xxxxx" is the first half of the password for the mailserver. It is terminated where an octothorpe ("#") appears in the password.  I have attempted to escape the octothorpe with a backslash, as well as enclosing the password in either single or double quotes. All attempts generate the same error.

### Steps To Reproduce:

1. Configure notify to attempt to use SMTP with a password that contains an octothorpe ("#")
2. Run notify
3. See error

**Comment by ehsandeep** [comment]
@ossumpossum thanks for reporting this, now fixed in the latest release.
