### ISSUE TITLE
Threading support for slack webook

### ISSUE THREAD

**Issue by mostwanted002** [projectdiscovery/notify#26]
This is a feature request.
A way to reply in a slack thread by providing a timestamp, a channel ID, and the Slack API Key in the command line.

**Comment by ehsandeep** [comment]
This can be optionally supported, for example when the user specifies `slack_threads: true` under config block.

```yaml
slack: true
slack_webhook_url: https://a.b.c
slack_username: test
slack_channel: test
slack_threads: true
