### ISSUE TITLE
compilation terminated. error when installed intercept 

### ISSUE THREAD

**Issue by mohammed-sec2010** [projectdiscovery/notify#27]
ali@ali:~$ GO111MODULE=on go get -v -u github.com/projectdiscovery/notify/cmd/intercept

output:
go: github.com/projectdiscovery/notify/cmd/intercept upgrade => v0.0.0-20210217203733-c03d0cfcf351
go: github.com/logrusorgru/aurora upgrade => v2.0.3+incompatible
go: github.com/projectdiscovery/gologger upgrade => v1.1.4
go: github.com/projectdiscovery/collaborator upgrade => v0.0.2
go: golang.org/x/sys upgrade => v0.0.0-20210228012217-479acdf4ea46
go: downloading github.com/projectdiscovery/gologger v1.1.4
go: downloading github.com/projectdiscovery/collaborator v0.0.2
go: downloading golang.org/x/sys v0.0.0-20210228012217-479acdf4ea46
go: github.com/modern-go/reflect2 upgrade => v1.0.1
go: github.com/modern-go/concurrent upgrade => v0.0.0-20180306012644-bacd9c7ef1dd
github.com/projectdiscovery/gologger/levels
github.com/modern-go/concurrent
github.com/projectdiscovery/gologger/writer
github.com/google/gopacket/pcap
# github.com/google/gopacket/pcap
go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
github.com/modern-go/reflect2
github.com/json-iterator/go
github.com/projectdiscovery/gologger/formatter
github.com/projectdiscovery/gologger

**Comment by ehsandeep** [comment]
@mohammed-sec2010 make sure to install `apt install -y libpcap-dev`

**Comment by mohammed-sec2010** [comment]
thanks ...solved it

**Comment by mohammed-sec2010** [comment]
Hi
is there any problem for intercept biid in the latest version of burpsuite ?
ali@ali:~/go/bin$ sudo ./intercept 
Attempting to intercept BIID
BIID found: test
ali@ali:~/go/bin$ sudo ./intercept  -h
Attempting to intercept BIID
BIID found: test

ali@ali:~/go/bin$ sudo ./intercept  
Attempting to intercept BIID
BIID found: test

**Comment by mohammed-sec2010** [comment]
![test](https://user-images.githubusercontent.com/11797933/109471954-92abc580-7a82-11eb-9ab6-1e31980beb63.PNG)
Hi
I found biid in wireshark but we can not find it in intercept tool , why?

**Comment by ehsandeep** [comment]
@mohammed-sec2010 looks like you have and enabled the default `biid` value in the config file, make sure to comment that line to intercept the biid.

**Comment by mohammed-sec2010** [comment]
Hi
where can I find the config file?

**Comment by ehsandeep** [comment]
> Hi
> where can I find the config file?

`$HOME/.config/notify/notify.conf`

**Comment by mohammed-sec2010** [comment]
Hi
my problem is not with notify tool, my problem is the intercept tool can not capture the Biid of burpsuite when I click run over unencrypted HTTP in the burpsuite 
![test3](https://user-images.githubusercontent.com/11797933/109473696-b40db100-7a84-11eb-9848-6e3f60148bd3.PNG)

**Comment by Mzack9999** [comment]
This is working as intended, as, in fact, during the polling health check, the BIID used is `test`, which is correctly captured. You should start the `intercept` utility when you are in the burp collaborator window already and before clicking on [poll now](https://portswigger.net/burp/documentation/desktop/images/support/using_burp_collaborator_client_4.jpg)

**Comment by mohammed-sec2010** [comment]
you are right ,thanks.
