### ISSUE TITLE
error to save configuration in  Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

### ISSUE THREAD

**Issue by mohammed-sec2010** [projectdiscovery/notify#28]
![test](https://user-images.githubusercontent.com/11797933/109512845-90169380-7ab5-11eb-9a9c-f1f1b07332df.PNG)

it is works fine in ubuntu but it is not working in debian to save files from the terminal command

**Comment by mohammed-sec2010** [comment]
it is working to push the result to telegram with the below command:
 echo 'wewe' | ./notify -telegram 
but it is not working to push the result to telegram  when the notify tool to listen to burp collaborator:
   ./notify -telegram  -no-color
![test](https://user-images.githubusercontent.com/11797933/109517805-b7bc2a80-7aba-11eb-97c8-5164869a833a.PNG)

**Comment by ehsandeep** [comment]
Hi @mohammed-sec2010, 

As listed in the readme:-

> Telegram notification does not support burp collaborator.

**Comment by mohammed-sec2010** [comment]
yeah, you are right, could you please add an option  to specify  path of notify.conf because I want to save the configuration in another folder

**Comment by mohammed-sec2010** [comment]
yeah, you are right, could you please add an option  to specify  path of notify.conf because I want to save the configuration in another folder

**Comment by ehsandeep** [comment]
thank you, I will open a new issue for this!
