### ISSUE TITLE
can notify get full request like burpsuite (external service interaction)>?

### ISSUE THREAD

**Issue by mohammed-sec2010** [projectdiscovery/notify#30]
Hi
can notify get full request like burpsuite (external service interaction)> ? like below photo :
![test3](https://user-images.githubusercontent.com/11797933/109691275-54082f00-7b98-11eb-8645-df14eb4cd77e.PNG)

**Comment by ehsandeep** [comment]
Hi @mohammed-sec2010,

Yes, Notify with discord, slack support this as you can see here https://github.com/projectdiscovery/notify/blob/master/static/notify-run.png, also feel free to join discord server or Github discussion board for questions.

**Comment by mohammed-sec2010** [comment]
no it sent only of burp collaborator request, I have a request that vulnerable to blind XSS vul and I received this below result in slack :
The collaborator server received a DNS lookup of type  for the domain name qqkhn23cn7b3gutcw0b2jnoy18sej97y.burpcollaborator.netfrom X.253.X.X at 2021-03-02 20:28:32.028 +0300 +03:
z�qqkhn23cn7b3gutcw0b2jnoy18sej97yburpcollaboratornet��

I want to receive the full vulnerable request like https://xsshunter.com/app , you got my point?

**Comment by ehsandeep** [comment]
I got your point, and unfortunately no it is not supported and out of scope for this project.
