### ISSUE TITLE
Notify taking time to send output in Slack

### ISSUE THREAD

**Issue by infosecsanyam261** [projectdiscovery/notify#38]
Hi Team,

I have a one query, I configured all the settings in the config file for slack. I received the response in the slack but it will take some time..

if i need subdomain for particular domain, so i used the command - `subfinder -d bugpoc.com | notify` - it send one subdomain in 5 sec then another subdomain sending in 10 sec. If i send directly `subfinder -d bugpoc.com` then it will take around 2 sec to fetch all subdomains and even i used `slackcat subfinder -d bugpoc.com | slackcat` for this it will send all subdomain in one shot within 2 sec but in notify it will take too much time. Can you please help?

PFB Screenshot
![image](https://user-images.githubusercontent.com/45365465/116784916-69c0a480-aab4-11eb-8517-1be291540b95.png)

**Comment by ehsandeep** [comment]
@infosecsanyam261 notify sends data per line, so each found subdomain gets posted into slack line by line, but 5-10 seconds is not expected and not reproducible, for me I can see results into slack as I see results into CLI, make sure it's not related to the local network.

**Comment by infosecsanyam261** [comment]
Hi Ehsandeep,

As i noticed, when i used normal command without notify then i get results within 1 seconds. when i used pipe command to push data to slack then i get results in cli and slack very slowly. If you need video for this then i will share. Also can you please let me know is there anything need to change in the config file?

**Comment by ehsandeep** [comment]
@infosecsanyam261, thanks for additional input and this expected, notify sends data per line, so 100 results mean 100 API requests to slack, in next update will be adding support for the bulk push that user can configure as per need.

Closing this as this is expected behavior.

Related issue - https://github.com/projectdiscovery/notify/issues/39

**Comment by ehsandeep** [comment]
@infosecsanyam261 latest version of notify supports bulk processing, check out the example uses for using `bulk` flag.
