### ISSUE TITLE
telegram notifications with "*" don't get sent

### ISSUE THREAD

**Issue by molitona** [projectdiscovery/notify#394]
telegram notifications with "*" don't get sent always. please fix

![Screenshot from 2024-07-18 12-24-40](https://github.com/user-attachments/assets/adf82105-cd9c-4ba6-a98a-b0b21f3ad5a7)

**Comment by molitona** [comment]
also "[" and "`" 

total = 3 special chars

![Screenshot from 2024-07-19 12-03-22](https://github.com/user-attachments/assets/851828c3-63bd-49b0-a2e6-f0a225fe018f)

**Comment by dogancanbakir** [comment]
We provide support for multiple formats: None/Markdown/MarkdownV2/HTML (https://core.telegram.org/bots/api#formatting-options). If you need to send special characters, ensure that you set `telegram_parsemode` in the config to the correct one. For this case, try setting `telegram_parsemode` to `None`.
