### ISSUE TITLE
--discord-webhook-url argument doesn't seem to be working.

### ISSUE THREAD

**Issue by DEMON1A** [projectdiscovery/notify#40]
I dunno if i'm wrong or not. but i want to use notify for multi tasks on my discord server. so i guessed `--discord-webhook-url` argument could be used to set two different webhooks on every command. but when i add the webhook URL as an argument value. the result keep getting sent into the webhook on notify config itself.

I deleted the config and tried again, and nothing happens all that happens there is that notify keeps telling me that the config file doesn't exists.

**Comment by 0xWise64** [comment]
The same problem here when using the configuration file, then adding the argument `--discord-webhook-url` notify will continue to be sent to the webhook in the configuration file, so is there any option to send the notification in two or multiple chats on the Discord?

**Comment by ehsandeep** [comment]
@DEMON1A @0xWise64 This is intended behavior as initially, we were not sure about this use case, here is GH issue to add support for this in future releases.
