### ISSUE TITLE
unable to generate biid in wsl to burp

### ISSUE THREAD

**Issue by balook** [projectdiscovery/notify#5]
unable to generate biid in wsl to burp

Error:

BIID found, using:
[FTL] Could not run notifier: BIID not specified or not found

**Comment by bauthard** [comment]
Hi @balook, 

Please include the details of the command. 

Here are the steps to follow:- https://github.com/projectdiscovery/notify#intercept-biid

**Comment by balook** [comment]
sudo notify -intercept-biid

**Comment by balook** [comment]
i ranned with as loin as root too

**Comment by bauthard** [comment]
I see, and yes it's a known issue for the Windows platform, in that case, as listed in the readme you need to use Wireshark to obtain the `biid` that you case use with notify. 

> You can obtain the biid with Wireshark on any platform and configure it within the config file.

**Comment by balook** [comment]
As i searched in google i didnt get the answer how to get the biid value ....can u guide ?

**Comment by parthmalhotra** [comment]
Try this https://twitter.com/Parth_Malhotra/status/1325744663274291200

**Comment by bauthard** [comment]
Thank you @parthmalhotra, @balook please have a look at the above method.
