### ISSUE TITLE
telegram notification drops message containing the word "Hourly"

### ISSUE THREAD

**Issue by KrE80r** [projectdiscovery/notify#51]
A bit weird issue here on version 0.0.2

`echo Hourly | notify -telegram -telegram-api-key <API>-telegram-chat-id <ID>`

Would work as expected sending the message to telegram, but

`echo something Hourly | notify -telegram -telegram-api-key <API>-telegram-chat-id <ID>`

Does not send anything to telegram. Not sure if this a telegram issue or notify itself.

**Comment by ehsandeep** [comment]
@KrE80r this should be fixed with the latest release.
