### ISSUE TITLE
Rate Limit treatment

### ISSUE THREAD

**Issue by c3l3si4n** [projectdiscovery/notify#58]
It would be nice for notify to automatically detect when it is being blocked and implement a exponential backoff system where it keeps retrying to send messages in exponentially greater delays.
Example:

notify -> 429
sleep 2 seconds
notify -> 429
sleep 4 seconds
notify -> 429
sleep 8 seconds
notify -> 429
sleep 16 seconds
notify -> 200
leave program

**Comment by ehsandeep** [comment]
Hi @c3l3si4n,

Thanks for raising an issue, Notify deals with data to post on multiple platforms. Having some automated backoff system may solve this issue, but there will be more problems to deal with that support, such as tracking and keeping data in sync to ensure it doesn't send duplicate data or drop unsend data, and that will create additional overhead. As a result, we will not be able to implement such a feature at this time.
