### ISSUE TITLE
Notify config file isn't loading 

### ISSUE THREAD

**Issue by sh0tal** [projectdiscovery/notify#69]
Hello guys,

I am using a fully updated kali Linux on a VPS.
Notify Version: 0.0.2

 As i installed notify and runt it as root, i got this message:

```
Running as root, skipping config file write to avoid permissions issues: /root/.config/notify/notify.conf
Could not read configuration file /root/.config/notify/notify.conf - ignoring error: open /root/.config/notify/noti
fy.conf: no such file or directory
```
Then proceeded to run it as a normal user 
and i got this message:
```
Found existing config file: /home/user/.config/notify/notify.conf
Could not read configuration file /home/user/.config/notify/notify.conf - ignoring error: EOF
```

I edited the .config file with my webhook and also removed the comment from discord: true
Then i copied the notify.conf from the /home/user/.config/notify directory to the root directory: /root/.config/notify/ (because it was missing from the root directory)

And run it again.
The message i got is this one:
```
Found existing config file: /root/.config/notify/notify.conf
Could not read configuration file /root/.config/notify/notify.conf - ignoring error: yaml: line 8: did not find expected key
```

**After that i  tried again with the normal user and it WORKED.**
But running it as root causes the error i mentioned above.

**what is the problem and it cannot read the configuration file when running it as root?**

**Comment by ehsandeep** [comment]
@sh0tal soon we will be pushing [new version](https://github.com/projectdiscovery/notify/projects/1) of notify, we can confirm this is already fixed in the dev version.

**Comment by sh0tal** [comment]
Hello @ehsandeep 

Okay, thank you for your answer.
