### ISSUE TITLE
Add Rate Limit Support 

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/notify#79]
Currently, it's not possible to control the request rate, leading to multiple services hitting rate-limit and discarding the msg which also breaks the automation pipeline.

This support can be added similar to projectdiscovery/subfinder#449

**Comment by ehsandeep** [comment]
This support can be added similar to https://github.com/projectdiscovery/subfinder/pull/449

**Comment by ehsandeep** [comment]
@DhiyaneshGeek now `rl` flag can be used to specify request to send per second.
